import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Header } from '@/components/Header';
import { Screen, Card } from '@/components/Screen';
import { ActionButton } from '@/components/ActionButton';
import { ResultCard } from '@/components/ResultCard';
import { useColors } from '@/hooks/useColors';
import { apiRequest, askAI, getSession, saveHistory } from '@/lib/api';
import { speakText } from '@/lib/speech';
import { getProfile, incrementProgress } from '@/lib/storage';

type Lesson = { id: string; title: string; description: string; skill_type: string; status?: string; last_score?: number | null };
type Content = { concept: string; examples: string[]; practice: string };
export default function LearningJourneyScreen() {
  const colors = useColors();
  const [lessons, setLessons] = useState<Lesson[]>([]);
  const [current, setCurrent] = useState<Lesson | null>(null);
  const [content, setContent] = useState<Content | null>(null);
  const [score, setScore] = useState('');
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const profile = await getProfile(); const session = await getSession().catch(() => null); const userId = session?.id ? String(session.id) : 'guest'; const data = await apiRequest<{ lessons: Lesson[]; current_level: string; mode: string }>(`/journey/next?userId=${encodeURIComponent(userId)}`); setLessons(data.lessons || []); setCurrent(data.lessons?.[0] || null); if (data.lessons?.[0]) { const lesson = data.lessons[0]; setContent(await apiRequest<Content>(`/journey/lesson-content/${lesson.id}?level=${encodeURIComponent('Intermediate')}&goal=${encodeURIComponent(profile.careerGoal)}&nativeLang=${encodeURIComponent(profile.language)}&name=${encodeURIComponent(profile.name)}&skills=${encodeURIComponent(profile.skills)}`)); } } catch (error) { Alert.alert('Journey unavailable', error instanceof Error ? error.message : 'Please try again.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async () => { if (!current) return; try { const session = await getSession().catch(() => null); await apiRequest('/journey/submit-result', { method: 'POST', body: JSON.stringify({ lesson_id: current.id, score: Number(score) || 0, userId: session?.id ? String(session.id) : 'guest' }) }); await incrementProgress('englishMinutes'); Alert.alert('Progress saved', 'Your next review is scheduled with SM-2.'); setScore(''); await load(); } catch (error) { Alert.alert('Could not save', error instanceof Error ? error.message : 'Please try again.'); } };
  if (loading) return <Screen><Header title="Learning Journey" subtitle="Your spaced-repetition roadmap" showBack /><Text style={[styles.loading, { color: colors.mutedForeground }]}>Loading your next lesson…</Text></Screen>;
  return <Screen><Header title="Learning Journey" subtitle="Learn, practise, review and build mastery" showBack /><View style={styles.list}>{lessons.slice(0, 8).map((lesson) => <TouchableOpacity key={lesson.id} onPress={() => { setCurrent(lesson); setContent(null); }}><Card style={current?.id === lesson.id ? { borderColor: colors.primary } : undefined}><Text style={[styles.lessonTitle, { color: colors.foreground }]}>{lesson.title}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{lesson.skill_type} · {lesson.status || 'lesson'}{lesson.last_score != null ? ` · last score ${lesson.last_score}` : ''}</Text><Text style={[styles.description, { color: colors.mutedForeground }]}>{lesson.description}</Text></Card></TouchableOpacity>)}</View>{current && <View style={styles.focus}><ActionButton title={content ? 'Refresh lesson' : 'Open lesson'} variant="outline" onPress={() => { const profilePromise = getProfile(); void profilePromise.then((profile) => apiRequest<Content>(`/journey/lesson-content/${current.id}?level=Intermediate&goal=${encodeURIComponent(profile.careerGoal)}&nativeLang=${encodeURIComponent(profile.language)}&name=${encodeURIComponent(profile.name)}&skills=${encodeURIComponent(profile.skills)}`).then(setContent).catch((error) => Alert.alert('Could not open lesson', error.message))); }} />{content ? <><ResultCard title={current.title} content={`${content.concept}\n\nExamples:\n${content.examples.map((item) => `• ${item}`).join('\n')}\n\nPractice:\n${content.practice}`} onSave={() => void saveHistory('learning-journey', current.title, `${content.concept}\n\n${content.examples.join('\n')}\n\n${content.practice}`).then(() => Alert.alert('Saved', 'Lesson added to history.'))} /><View style={styles.actions}><ActionButton title="Listen" variant="outline" onPress={() => speakText(`${content.concept}. ${content.examples.join('. ')}. Practice: ${content.practice}`)} /><ActionButton title="Mark score / 100" onPress={() => void submit()} /></View><TextInput value={score} onChangeText={setScore} keyboardType="number-pad" placeholder="Enter your score from 0 to 100 before saving" placeholderTextColor={colors.mutedForeground} style={[styles.score, { color: colors.foreground, backgroundColor: colors.card, borderColor: colors.border }]} /></> : null}</View>}</Screen>;
}
const styles = StyleSheet.create({ loading: { textAlign: 'center', marginTop: 50, fontFamily: 'Inter_400Regular' }, list: { paddingHorizontal: 20, gap: 8 }, lessonTitle: { fontFamily: 'Inter_700Bold', fontSize: 16 }, meta: { fontFamily: 'Inter_500Medium', fontSize: 12, marginTop: 5 }, description: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginTop: 7 }, focus: { marginTop: 16 }, actions: { flexDirection: 'row', paddingHorizontal: 20, gap: 10, marginTop: 10 }, score: { marginHorizontal: 20, marginTop: 10, borderWidth: StyleSheet.hairlineWidth, borderRadius: 10, padding: 12 } });